question_data =  [{"category": "Geography", "type": "boolean", "difficulty": "easy",
                                                  "question": "San Marino is the only country completely surrounded by another country.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                                  "question": "There was a satirical candidate named &quot;Deez Nuts&quot; running in the 2016 US presidential elections.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Science: Computers", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "Ada Lovelace is often considered the first computer programmer.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Mythology", "type": "boolean", "difficulty": "medium",
                                                  "question": "According to Norse mythology, Loki is a mother.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Entertainment: Video Games", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "hard",
                                                  "question": "Switzerland has four national languages, English being one of them.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "General Knowledge", "type": "boolean",
                                                  "difficulty": "easy",
                                                  "question": "The National Animal of Scotland is the Unicorn.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                                  "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]},
                                                 {"category": "Art", "type": "boolean", "difficulty": "medium",
                                                  "question": "Venus of Willendorf is one of the earliest works of art, depicting the planets Mars and Venus embrace in the heavens at night.",
                                                  "correct_answer": "False", "incorrect_answers": ["True"]},
                                                 {"category": "Entertainment: Music", "type": "boolean",
                                                  "difficulty": "medium",
                                                  "question": "&quot;Neutral Milk Hotel&quot; is a real band.",
                                                  "correct_answer": "True", "incorrect_answers": ["False"]}]
